stages:
  preprocess:
    cmd: python transform.py
    deps:
      - data/processed/Gaming and Mental Health.csv
      - transform.py
      - transformer/
    outs:
      - data/processed/data.csv
      - data/raw/data.parquet
